---
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
